function log_staircase_info_v2(block, trial, quad, motionDirec, responseLabel, staircase, staircase_name)
    fprintf(['Block %d, Trial %d: Quad = %d, Mot = %d, responseLabel = %s\n' ...
        '%s.reversals = %d  %s.stimuluslevel = %.f\n ' ...
        '%s.direction = %d  %s.step = %d\n'], ...
        block, trial, quad, motionDirec, responseLabel,...
        staircase_name, staircase.reversals, ...
        staircase_name, staircase.stimuluslevel, ...
        staircase_name, staircase.direction, ...
        staircase_name, staircase.step);
end
