function log_staircase_info(block, trial, quad, motionDirec, responseLabel,responseCorrect, staircase, staircase_name)
    fprintf(['Block %d, Trial %d: Quad = %d, Mot = %d, responseLabel = %s, responseCorrect = %d\n' ...
        '%s.reversals = %d  %s.stimuluslevel = %.f\n ' ...
        '%s.direction = %d  %s.correctResponses = %d\n %s.incorrectResponses = %d\n, %s.step = %d\n'], ...
        block, trial, quad, motionDirec, responseLabel,responseCorrect, ...
        staircase_name, staircase.reversals, ...
        staircase_name, staircase.stimuluslevel, ...
        staircase_name, staircase.direction, ...
        staircase_name, staircase.correctResponses, ...
        staircase_name, staircase.incorrectResponses, ...
        staircase_name, staircase.step);
end
